In [1]:
import numpy as np

# Numpy Array

In [9]:
myarr = np.array([[1,23,6,345,88]], np.int64)

In [10]:
myarr[0,1] # accessing element

23

In [11]:
myarr.shape # 1 row 5 columns

(1, 5)

In [12]:
myarr.dtype

dtype('int64')

In [13]:
myarr[0,4] = 2345
myarr

array([[   1,   23,    6,  345, 2345]], dtype=int64)

In [14]:
myarr.size

5

In [16]:
np.array({34,234,54,34})

array({34, 234, 54}, dtype=object)

In [19]:
zeroes = np.zeros((2,5))
zeroes # Array of zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
range = np.arange(15)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,50,10)
lspace # 10 Equal difference between integers in [1,50]

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
emp = np.empty((3,5))
emp # empty array of given size with random integers

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
iden = np.identity(8)
iden # identity matrix of size 8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
ran = np.arange(99)
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr = ran.reshape(3,33) # Reshape array but all elements should be included
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel() # converts again into 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
ar.sum(axis=0) # sum of all row elements for each column

array([12,  8,  9])

In [41]:
ar.sum(axis=1) # sum of all column elements for each row

array([ 6, 15,  8])

In [43]:
ar.T # Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
for item in ar.flat:
    print(item) # provides each element of matrix

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim # number of dimensions

2

In [46]:
print(ar.size)
print(ar.nbytes)

9
36


In [47]:
one = np.array([1,3,4,634,23,243])

In [48]:
one.argmax() # Returns the index of max element

3

In [49]:
one.argmin() # Returns the index of min element

0

In [50]:
one.argsort() # Provide order of indices which will sort the array

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [52]:
print(ar.argmin(axis=1))
print(ar.argmax(axis=0))

[0 0 2]
[2 1 1]


In [53]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [54]:
ar2 = np.array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [55]:
ar+ar2 # add the two matrix and this can't be done in list.

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [56]:
ar*ar2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [57]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [60]:
print(ar.sum())
print(ar.max())
print(ar.min())

29
7
0


In [61]:
np.where(ar>5) # Return index of the element which are greater than 5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [62]:
np.count_nonzero(ar)

8

In [63]:
np.nonzero(iden)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64))

In [66]:
import sys
py_ar = [1,23,4,55]
np_ar = np.array(py_ar)

In [68]:
print(sys.getsizeof(1)*len(py_ar))
print(np_ar.itemsize*np_ar.size)
# This shows the difference between the bytes of the two arrays

112
16


In [69]:
# Read numpy array attributes and methods on scipy.org